services:
    ### Configurações de e-mail
    jhv_user.mailer:
        class     : "%jhv_user.parameter.class.mailer%"
        arguments :
            - "@mailer"
            - "@router"
            - "@twig"
            - "%jhv_user.parameter.templates%"
            - "%jhv_user.parameter.emails%"