services:	
    ### Roteamento de registro
    jhv_user.router:
        class     : "%jhv_user.parameter.class.router%"
        public    : false
        arguments :
            - "%jhv_user.parameter.routes%"
        tags      :
            - { name: routing.loader }